# Generated by Django 5.2 on 2025-04-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
        ("store", "0003_alter_variation_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, null=True, to="store.variation"),
        ),
    ]
