# Generated by Django 5.2 on 2025-05-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_cartitem_user_alter_cartitem_cart"),
        ("store", "0004_alter_product_category_alter_variation_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
