# Generated by Django 5.2 on 2026-01-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_productgallery_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="variation",
            constraint=models.UniqueConstraint(
                fields=("product", "variation_category", "variation_value"),
                name="unique_product_variation",
            ),
        ),
    ]
