# Generated by Django 5.2 on 2025-05-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_orderproduct_color_remove_orderproduct_size_and_more"),
        ("store", "0004_alter_product_category_alter_variation_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="variation",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_products",
                to="store.variation",
            ),
        ),
    ]
