# Generated by Django 5.2 on 2025-05-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_remove_orderproduct_variation_and_more"),
        ("store", "0004_alter_product_category_alter_variation_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
